spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ajsihdiwq
            client-secret: qwjhqwgeqwhwq
          github:
            client-id: Ov23liTbBJgeP6EH2mna
            client-secret: ENC(T4JUwF2DdoIRjma3ZhtI4XezEfK6CsPfgNTaDIZZfYT9CgDK6wttBetnwkxn2F9v5uHIYhSwFVU=)
          linkedin: # <--- custom provider ID
            client-id: your-client-id
            client-secret: your-client-secret
            scope:
              - r_liteprofile
              - r_emailaddress
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: LinkedIn
            client-authentication-method: post
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            user-name-attribute: id


jasypt:
  encryptor:
    password: JmZV8pnQeUcOovP
    algorithm: PBEWithMD5AndDES